### ISSUE TITLE
make test errors

### ISSUE THREAD

**Issue by kbrevs** [sestaton/HMMER2GO#11]
Hey - I'm getting these errors when running make test:

PERL_DL_NONLAZY=1 "/usr/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/00-load.t ........ 1/3 # Testing HMMER2GO 0.17.2, Perl 5.022001, /usr/bin/perl
t/00-load.t ........ ok   
t/01-fetchmap.t .... ok   
t/02-getorf.t ...... ok     
t/03-run.t ......... ok     
t/04-mapterms.t .... ok   
t/05-map2gaf.t ..... ok   
t/06-pfamsearch.t .. 1/10 Use of uninitialized value $dbnum in concatenation (.) or string at /home/beetle/Downloads/hmmer2go/HMMER2GO-0.17.2/blib/lib/HMMER2GO/Command/pfamsearch.pm line 94.
t/06-pfamsearch.t .. 2/10 
#   Failed test 'Found the correct number of HMMs for the search term'
#   at t/06-pfamsearch.t line 39.
#          got: undef
#     expected: '7'

#   Failed test 'Found the HMMs in the correct number of databases'
#   at t/06-pfamsearch.t line 40.
#          got: undef
#     expected: '4'

#   Failed test 'Wrote the correct number of descriptions to the output file'
#   at t/06-pfamsearch.t line 51.
#          got: undef
#     expected: '10'
Use of uninitialized value $dbnum in concatenation (.) or string at /home/beetle/Downloads/hmmer2go/HMMER2GO-0.17.2/blib/lib/HMMER2GO/Command/pfamsearch.pm line 89.
t/06-pfamsearch.t .. 6/10 
#   Failed test 'Fetched the correct number of HMMs for the search term'
#   at t/06-pfamsearch.t line 61.
#          got: undef
#     expected: '10'
Use of uninitialized value $hmmnum in addition (+) at t/06-pfamsearch.t line 64.
# Looks like you planned 10 tests but ran 7.
# Looks like you failed 4 tests of 7 run.
# Looks like your test exited with 255 just after 7.
t/06-pfamsearch.t .. Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 7/10 subtests 
t/07-customdb.t .... ok   

Test Summary Report
-------------------
t/06-pfamsearch.t (Wstat: 65280 Tests: 7 Failed: 4)
  Failed tests:  2-3, 5, 7
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 10 tests but ran 7.
Files=8, Tests=51, 36 wallclock secs ( 0.06 usr  0.01 sys + 13.57 cusr  2.41 csys = 16.05 CPU)
Result: FAIL
Failed 1/8 test programs. 4/51 subtests failed.
Makefile:891: recipe for target 'test_dynamic' failed
make: *** [test_dynamic] Error 255

Thanks,

**Comment by sestaton** [comment]
Thanks for the report, I've marked it a bug and will look into it.

**Comment by sestaton** [comment]
Could you give it another try with the updates I've applied to the master branch? I'll make a new release shortly.

**Comment by kbrevs** [comment]
Looks like that fixed it! Thanks.
