### ISSUE TITLE
small changes to the Demostration script

### ISSUE THREAD

**Issue by glucksfall** [sestaton/HMMER2GO#18]
Hello,
First, I have to thank you for your project. I successfully run the tutorial steps on a genome sequence downloaded from NCBI and now looking at the results. For curiosity, I tried the Demonstration script, and there are two changes to make:

The `Arabidopsis_thaliana.TAIR10.22.cdna.all.fa.gz` was renamed to `Arabidopsis_thaliana.TAIR10.cdna.all.fa.gz`, and the ftp link to `http://ftp.gramene.org/release-60/fasta/arabidopsis_thaliana/cdna/`

Just that.

Thank you for your time, 
best regards

**Comment by sestaton** [comment]
Thank you for the comment I'll have a look and add the suggestions.

**Comment by sestaton** [comment]
Thank you for the comments. I've updated the [Demonstration](https://github.com/sestaton/HMMER2GO/wiki/Demonstraton) page with a full working example that will fetch the latest TAIR CDSs and run the analysis.
