### ISSUE TITLE
HMM file b

### ISSUE THREAD

**Issue by zijiangyang** [sestaton/HMMER2GO#19]
Hi, I tried to use the hmmer2go run in the command line and it reported the following error:

Error: File existence/permissions problem in trying to open HMM file b.
HMM file b not found (nor an .h3m binary of it); also looked in PFAMDB

How should I fix that? Thx in advance!

**Comment by sestaton** [comment]
Hi, Can you show the full command? It looks like perhaps your Pfam database was not formatted with `hmmpress` prior to trying to use it.

**Comment by zijiangyang** [comment]
> Hi, Can you show the full command? It looks like perhaps your Pfam database was not formatted with hmmpress prior to trying to use it.

thx! just formatted the hmm file and it works fine
