### ISSUE TITLE
-nm option

### ISSUE THREAD

**Issue by swiddison** [sestaton/HMMER2GO#22]
I am struggling to understand the -nm option. The manual says:
-nm, --nomet
      Do not report only those ORFs starting with Methionine (Default: Yes).

So if I want to report only those ORFs that start with a methionine I should choose No. I have tried various permutations e.g. '-nm No and -nm False' but the output is the same as if I had run the default. I also don't get an error to tell me either is incorrect.

How do I turn this option 'off'?

**Comment by sestaton** [comment]
Sorry for the confusion. The default is to only report ORFs starting with Met. If you supply that option (`-nm` or `--nomet`) it will report all ORFs, including those not starting with Met.

In your case, it may be that there were no other ORFs so the option had no impact on the results.

**Comment by swiddison** [comment]
Thanks for getting back to me, I tried without the -nm and was still getting orfs that don't start with met.
What fixed it for me was using -t 1 to only report 'Translation of regions between START and STOP codons.'

**Comment by sestaton** [comment]
Thank you for the comments. I've added this to the TODO list/file and I'll try to incorporate this as a default in the next release to make the output be closer to what is expected as the default.
