### ISSUE TITLE
Unable to Connect to ftp.geneontology.org

### ISSUE THREAD

**Issue by Wolves-printer** [sestaton/HMMER2GO#25]
Dear Evan Staton,
Hello! Thank you a lot for benefiting the community by writing the wonderful HMMER2GO package for Gene Ontology mapping. However, I found difficulties connecting to ftp.geneontology,org during my installation of HMMER2GO 0.18.0 in the Linux Ubuntu system. I first tried to use the git command to install HMMER2GO, but the installation failed to show 
`Cannot connect to ftp.geneontology.org: Connection refused will retry. at /root/HMMER2GO-0.18.0/blib/lib/HMMER2GO/Command/mapterms.pm line 162.`.
Alternatively, I tried to install it by downloading the source code followed by make, make test and make install. However, during the make test, a similar issue occurred by showing that
```
root@DESKTOP-1G86O4Q:~/HMMER2GO-0.18.0# make test
PERL_DL_NONLAZY=1 "/usr/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/00-load.t ........ 1/3 # Testing HMMER2GO 0.18.0, Perl 5.030000, /usr/bin/perl
t/00-load.t ........ ok
t/01-fetchmap.t .... ok
t/02-getorf.t ...... ok
t/03-run.t ......... ok
t/04-mapterms.t .... 1/9 Cannot connect to ftp.geneontology.org: Connection refused will retry. at /root/HMMER2GO-0.18.0/blib/lib/HMMER2GO/Command/mapterms.pm line 162.
Cannot connect to ftp.geneontology.org: Connection refused will retry. at /root/HMMER2GO-0.18.0/blib/lib/HMMER2GO/Command/mapterms.pm line 162.
Cannot connect to ftp.geneontology.org: Connection refused will retry. at /root/HMMER2GO-0.18.0/blib/lib/HMMER2GO/Command/mapterms.pm line 162.
Cannot connect to ftp.geneontology.org: Connection refused will retry. at /root/HMMER2GO-0.18.0/blib/lib/HMMER2GO/Command/mapterms.pm line 162.

[ERROR]: Failed to get mapping file after multiple attempts: Can't call method "login" on an undefined value at /root/HMMER2GO-0.18.0/blib/lib/HMMER2GO/Command/mapterms.pm line 165.
 at /usr/local/share/perl/5.30.0/App/Cmd.pm line 473.
"blib/bin/hmmer2go mapterms -i t/test_data/t_orfs_long_Pfam-A.tblout -o t/test_data/t_long_Pfam-A_mapped_goterms.tsv -p t/test_data/pfam2go" unexpectedly returned exit value 111 at t/04-mapterms.t line 29.
# Looks like your test exited with 111 just after 1.
t/04-mapterms.t .... Dubious, test returned 111 (wstat 28416, 0x6f00)
Failed 8/9 subtests
t/05-map2gaf.t ..... ok
t/06-pfamsearch.t .. 2/10
#   Failed test 'Found the correct number of HMMs for the search term'
#   at t/06-pfamsearch.t line 39.
#          got: '103'
#     expected: '16'
```
It seems that the connection to ftp.geneontology.org was unsuccessful, but other commands (for example, getting ORF) seem to be working well. I was wondering how I could solve this problem. I tried to connect to ftp.geneontology.org through my windows browser but it also failed. I was wondering whether it would be a problem with the website. Thank you for taking the time to read this email, and hope to hear from you soon.
Best Regards,
Xiao Wang

**Comment by makrez** [comment]
Not sure if this issue is still looked at. I have a similar issue with both commands that are downloading data:

```
hmmer2go fetchmap -o pfam2go
```

Which returns the following error:

```
Cannot connect to ftp.geneontology.org: Connection timed out, will retry. at /usr/local/share/perl/5.26.1/HMMER2GO/Command/fetchmap.pm line 77.
```
The problem seems to be that the ftp address is wrong/down:

```
    $outfile //= 'pfam2go';

    my $host = 'ftp.geneontology.org';
    my $dir  = '/pub/go/external2go';
    my $file = 'pfam2go';
```

The same goes for the `map2gaf` command which downloads the `go.obo`. 

I assume that the tool would work fine if these files are downloaded manually and used as input in the command line. Could you possibly assist in how to get around this?

Kind regards

**Comment by robpade** [comment]
I recommend downloading (via `wget`, for example) the pfam2go and go.obo files. Download pfam2go from [http://current.geneontology.org/ontology/external2go/pfam2go](http://current.geneontology.org/ontology/external2go/pfam2go) and go.obo from [http://current.geneontology.org/ontology/go.obo](http://current.geneontology.org/ontology/go.obo). 

For `hmmer2go mapterms`, you can use the option `-p pfam2go` (where pfam2go is what you downloaded), while for `hmmer2go map2gaf` you can use the option `-g go.obo` (where go.obo is what you downloaded).

**Comment by sestaton** [comment]
Thanks for pointing out the new ontology locations @robpade. The FTP URLs need to be updated in this package and I'll try to get this done soon.

**Comment by sestaton** [comment]
Please try the latest version v0.18.1, which includes fixes for this issue. Thanks! Comment if you have more issues.
