### ISSUE TITLE
BioPerl dependency

### ISSUE THREAD

**Issue by fdchevalier** [sestaton/HMMER2GO#30]
Hello @sestaton ,

Thank you for developing and maintaining this tool.

During the test run, I got error messages regarding missing `Bio::DB::Taxonomy` module. This was due to the absence of BioPerl from my install. I think this module should be checked as prerequisite perl module in `Makefile.PL`.

**Comment by sestaton** [comment]
Thank you for the report. You are correct, it should be listed in the `Makefile.PL`.  The `cpanfile` and `Makefile.PL` should be in sync. 

This is a very easy fix so I will try to get it done asap.
